create table Entrada
(
    CODENTRADA varchar(8),
    PRECIO decimal(1,1),
    SESION decimal(1,0) NOT NULL,
    FECHA date NOT NULL,
    CODPELICULA varchar(8) NOT NULL,
    CODSALA varchar(8) NOT NULL,
    CONSTRAINT PK_ENTRADA PRIMARY KEY (CODENTRADA),
    CONSTRAINT FK_ENTRADA_PROYECTA FOREIGN KEY (SESION, FECHA, CODPELICULA, CODSALA) REFERENCES PROYECTA (SESION, FECHA, CODPELICULA, CODSALA)
);

create table Proyecta
(
    CODPELICULA varchar(8),
    CODSALA varchar(8),
    SESION decimal(1,0),
    FECHA date,
    ENTRADAS_VENDIDAS decimal(1,0),
    CONSTRAINT PK_PROYECTA PRIMARY KEY (SESION, FECHA, CODPELICULA, CODSALA),
    CONSTRAINT FK_PROYECTA_PELICULA FOREIGN KEY (CODPELICULA) REFERENCES PELICULA (CODPELICULA),
    CONSTRAINT FK_PROYECTA_SALA FOREIGN KEY (CODSALA) REFERENCES SALA (CODSALA),
    CONSTRAINT CK_PROYECTA_SESION CHECK (SESION IN (5,7,10))
);

create table Sala
(
    CODSALA varchar(8),
    AFORO decimal(1,0),
    CODCINE varchar(8) NOT NULL,
    CONSTRAINT PK_SALA PRIMARY KEY (CODSALA),
    CONSTRAINT FK_SALA_CINE FOREIGN KEY (CODCINE) REFERENCES CINE (CODCINE)
);

create table Pelicula
(
    CODPELICULA varchar(8),
    TITULO varchar(20),
    DURACION decimal(1,0),
    TIPO varchar(20),
    CODPELICULA_ORIGINAL varchar(8),
    CONSTRAINT PK_PELICULA PRIMARY KEY (CODPELICULA),
    CONSTRAINT CK_PELICULA_TIPO CHECK (TIPO IN ('ficcion', 'aventuras', 'terror')),
    CONSTRAINT UQ_PELICULA_TITULO UNIQUE (TITULO),
    CONSTRAINT FK_PELICULA_PELICULA_ORIGINAL FOREIGN KEY (CODPELICULA_ORIGINAL) REFERENCES PELICULA (CODPELICULA)
);

create table Cine
(
    CODCINE varchar(8),
    LOCALIDAD varchar(20),
    CONSTRAINT PK_CINE PRIMARY KEY (CODCINE)
);

create table Cine3D
(
    CODCINE varchar(8),
    NUMSALAS decimal(1,0),
    CONSTRAINT PK_CINE3D PRIMARY KEY (CODCINE),
    CONSTRAINT FK_CINE3D_CINE FOREIGN KEY (CODCINE) REFERENCES CINE (CODCINE)
);