create table Alumno
(
    DNIA varchar(8),
    NOMA varchar(20),
    APELLA varchar(20),
    DOMICILIOA varchar(20),
    F_NACIMIENTO date,
    F_INGRESO date,
    CONSTRAINT CP_ALUMNO PRIMARY KEY (DNIA)
);

create table Asignatura
(
    CODASIG varchar(8),
    NOMASIG varchar(20),
    CURSO decimal(1,0),
    CREDITOS decimal(1,0),
    TIPO varchar(20),
    DNIA varchar(8) NOT NULL,
    CODCARR varchar(8) NOT NULL,
    CONSTRAINT PK_ASIGNATURA PRIMARY KEY (CODASIG),
    CONSTRAINT CK_ASIGNATURA_TIPO CHECK (TIPO IN ('obligatoria','optativa','libre configuracion')),
    CONSTRAINT FK_ASIGNATURA_ALUMNO FOREIGN KEY (DNIA) REFERENCES ALUMNO (DNIA),
    CONSTRAINT UQ_ASIGNATURA_NOMASIG UNIQUE (NOMASIG),
    CONSTRAINT FK_ASIGNATURA_CODCARR FOREIGN KEY (CODCARR) REFERENCES CARRERA (CODCARR)
);

create table Carrera
(
    CODCARR varchar(8),
    NOMBREC varchar(20),
    DURACION decimal(1,0),
    CONSTRAINT PK_CARRERA PRIMARY KEY (CODCARR)
);

create table Profesor
(
    DNIP varchar(8),
    NOMP varchar(20),
    APELLIDOP varchar(20),
    DOMICILIOP varchar(20),
    CODASIG varchar(8) NOT NULL,
    CONSTRAINT PK_PROFESOR PRIMARY KEY (DNIP),
    CONSTRAINT FK_PROFESOR_ASIGNATURA FOREIGN KEY (CODASIG) REFERENCES ASIGNATURA (CODASIG)
);

create table Califica
(
    CODASIG varchar(20),
    DNIA varchar(8),
    DNIP varchar(8) NOT NULL,
    NOTA decimal(2,0),
    FECHA_CALIFICACION date,
    CONSTRAINT PK_CALIFICA PRIMARY KEY (CODASIG, DNIA),
    CONSTRAINT FK_CALIFICA_ASIGNATURA FOREIGN KEY (CODASIG) REFERENCES ASIGNATURA (CODASIG),
    CONSTRAINT FK_CALIFICA_ALUMNO FOREIGN KEY (DNIA) REFERENCES ALUMNO (DNIA),
    CONSTRAINT FK_CALIFICA_PROFESOR FOREIGN KEY (DNIP) REFERENCES PROFESOR (DNIP),
    CONSTRAINT UQ_CALIFICA_DNIP UNIQUE (DNIP)
);

create table Imparte
(
    DNIP varchar(8),
    CODASIG varchar(8),
    CONSTRAINT PK_IMPARTE PRIMARY KEY (DNIP, CODASIG),
    CONSTRAINT FK_IMPARTE_PROFESOR FOREIGN KEY (DNIP) REFERENCES PROFESOR (DNIP),
    CONSTRAINT FK_IMPARTE_ASIGNATURA FOREIGN KEY (CODASIG) REFERENCES ASIGNATURA (CODASIG)
);

create table AsignaturaM2
(
    CODASIG varchar(8),
    NOMASIG varchar(20),
    CURSO decimal(1,0),
    CREDITOS decimal(1,0),
    TIPO varchar(20),
    CODCARR varchar(8) NOT NULL,
    CONSTRAINT PK_ASIGNATURAM2 PRIMARY KEY (CODASIG),
    CONSTRAINT CK_ASIGNATURAM2_TIPO CHECK (TIPO IN ('obligatoria','optativa','libre configuracion')),
    CONSTRAINT UQ_ASIGNATURAM2_NOMASIG UNIQUE (NOMASIG),
    CONSTRAINT FK_ASIGNATURAM2_CODCARR FOREIGN KEY (CODCARR) REFERENCES CARRERA (CODCARR)
);

create table CalificaM2
(
    CODASIG varchar(20),
    DNIA varchar(8),
    DNIP varchar(8) NOT NULL,
    NOTA decimal(2,0),
    FECHA_CALIFICACION date,
    CONSTRAINT PK_CALIFICAM2 PRIMARY KEY (CODASIG, DNIA, DNIP),
    CONSTRAINT FK_CALIFICAM2_IMPARTE FOREIGN KEY (CODASIG, DNIP) REFERENCES IMPARTE (CODASIG, DNIP),
    CONSTRAINT FK_CALIFICAM2_ALUMNO FOREIGN KEY (DNIA) REFERENCES ALUMNO (DNIA),
    CONSTRAINT UQ_CALIFICAM2_DNIP UNIQUE (DNIP)
);

create table ProfesorM2
(
    DNIP varchar(8),
    NOMP varchar(20),
    APELLIDOP varchar(20),
    DOMICILIOP varchar(20),
    CODASIG varchar(8) NOT NULL,
    CONSTRAINT PK_PROFESORM2 PRIMARY KEY (DNIP),
    CONSTRAINT FK_PROFESORM2_ASIGNATURA FOREIGN KEY (CODASIG) REFERENCES ASIGNATURAM2 (CODASIG)
);