create table entrega
(
    ENOMBRE varchar(20),
    PNOMBRE varchar(20),
    CANTIDAD decimal(1,0),
    FECHA date,
    CONSTRAINT PK_ENTREGA PRIMARY KEY (ENOMBRE, PNOMBRE),
    CONSTRAINT FK_ENTREGA_ESTACION FOREIGN KEY (ENOMBRE) REFERENCES ESTACION (ENOMBRE),
    CONSTRAINT FK_ENTREGA_PRODUCTOR FOREIGN KEY (PNOMBRE) REFERENCES PRODUCTOR (PNOMBRE)
);

create table Estacion
(
    ENOMBRE varchar(20),
    TRANSFORMADORES decimal(1,0),
    CONSTRAINT PK_ESTACION PRIMARY KEY(ENOMBRE)
);

create table Red_Distribucion
(
    ENOMBRE varchar(20) not null,
    NUMRED decimal(1,0),
    LONGITUDMAXIMA decimal(1,0),
    CONSTRAINT PK_RED_DISTRIBUCION PRIMARY KEY (NUMRED),
    CONSTRAINT FK_RED_DISTRIBUCION_ESTACION FOREIGN KEY (ENOMBRE) REFERENCES ESTACION (ENOMBRE)
);

create table envia_energia
(
    NUMRED decimal(1,0),
    VOLUMEN decimal(1,1),
    CONSTRAINT PK_ENVIA_ENERGIA PRIMARY KEY (NUMRED),
    CONSTRAINT FK_ENVIA_ENERGIA_RED_DISTRIBUCION FOREIGN KEY (NUMRED) REFERENCES RED_DISTRIBUCION (NUMRED)
);

create table pertenece
(
    NUMRED decimal(1,0),
    CNOMBRE varchar(20),
    NUMACCIONES decimal(1,0),
    CONSTRAINT PK_PERTENECE PRIMARY KEY (NUMRED, CNOMBRE),
    CONSTRAINT FK_PERTENECE_RED_DISTRIBUCION FOREIGN KEY (NUMRED) REFERENCES RED_DISTRIBUCION (NUMRED),
    CONSTRAINT FK_PERTENECE_COMPANIA FOREIGN KEY (CNOMBRE) REFERENCES COMPANIA (CNOMBRE)
);

create table Compania
(
    CNOMBRE varchar(20),
    CAPITALSOCIAL varchar(20),
    CONSTRAINT PK_COMPANIA PRIMARY KEY (CNOMBRE)
);

create table Linea
(
    NUMRED decimal(1,0) NOT NULL,
    NLINEA decimal(2,0),
    LONGITUD decimal(10,2) NOT NULL,
    CONSTRAINT PK_LINEA PRIMARY KEY (NUMRED, NLINEA),
    CONSTRAINT FK_LINEA_RED_DISTRIBUCION FOREIGN KEY (NUMRED) REFERENCES RED_DISTRIBUCION (NUMRED)
);

create table Subestacion
(
    NSUBESTACION varchar(20),
    CAPACIDAD decimal(1,1),
    NLINEA decimal(2,0) NOT NULL,
    NUMRED decimal(1,0) NOT NULL,
    CONSTRAINT PK_SUBESTACION PRIMARY KEY (NSUBESTACION),
    CONSTRAINT FK_SUBESTACION_LINEA FOREIGN KEY (NUMRED, NLINEA) REFERENCES lINEA (NUMRED, NLINEA)
);

create table distribuye
(
    NSUBESTACION varchar(20),
    ZCODIGO varchar(20),
    CANTIDAD decimal(1,2),
    FECHA date,
    CONSTRAINT PK_DISTRIBUYE PRIMARY KEY (NSUBESTACION, ZCODIGO),
    CONSTRAINT FK_DISTRIBUYE_SUBESTACION FOREIGN KEY (NSUBESTACION) REFERENCES SUBESTACION (NSUBESTACION),
    CONSTRAINT FK_DISTRIBUYE_ZONA FOREIGN KEY (ZCODIGO) REFERENCES ZONA (ZCODIGO)
);

create table Zona
(
    ZCODIGO varchar(20),
    CONSUMOMEDIO decimal(1,2),
    CONSINSTITUCIONES decimal(1,2),
    CONSPARTICULARES decimal(1,2),
    CONSEMPRESAS decimal(1,2),
    PCODIGO decimal(1,0) NOT NULL,
    CONSTRAINT PK_ZONA PRIMARY KEY (ZCODIGO),
    CONSTRAINT FK_ZONA_PROVINCIA FOREIGN KEY (PCODIGO) REFERENCES PROVINCIA (PCODIGO),
    CONSTRAINT UQ_ZONA_PCODIGO UNIQUE (PCODIGO)
);

create table Provincia
(
    PCODIGO decimal(1,0),
    NOMBRE varchar(20),
    CONSTRAINT PK_PROVINCIA PRIMARY KEY (PCODIGO)
);

create table Productor
(
    PNOMBRE varchar(20),
    PRODMEDIA decimal(1,2),
    PRODMAXIMA decimal(1,2),
    FECHA date,
    CONSTRAINT PK_PRODUCTOR PRIMARY KEY (PNOMBRE)
);

create table Hidroelectrica
(
    PNOMBRE varchar(20),
    OCUPACION varchar(20),
    CAPMAXIMA decimal(2,0),
    NUMTURBINAS decimal(1,0),
    CONSTRAINT PK_HIDROELECTRICA PRIMARY KEY (PNOMBRE),
    CONSTRAINT FK_HIDROELECTRICA_PRODUCTOR FOREIGN KEY (PNOMBRE) REFERENCES PRODUCTOR (PNOMBRE)
);

create table Nuclear
(
    PNOMBRE varchar(20),
    NUMREACTORES decimal(1,0),
    PLUTONIO decimal(1,1),
    RESIDUOS decimal(1,1),
    CONSTRAINT PK_NUCLEAR PRIMARY KEY (PNOMBRE),
    CONSTRAINT FK_NUCLEAR_PRODUCTOR FOREIGN KEY (PNOMBRE) REFERENCES PRODUCTOR (PNOMBRE)
);

create table Solar
(
    PNOMBRE varchar(20),
    PANELES decimal(1,1),
    HORASSOL decimal(1,1),
    TIPO varchar(20),
    CONSTRAINT PK_SOLAR PRIMARY KEY (PNOMBRE),
    CONSTRAINT FK_SOLAR_PRODUCTOR FOREIGN KEY (PNOMBRE) REFERENCES PRODUCTOR (PNOMBRE),
    CONSTRAINT CK_SOLAR_TIPO CHECK (TIPO IN ('fotovoltaica','termodinamica'))
);

create table Termica
(
    PNOMBRE varchar(20),
    HORNOS decimal(1,0),
    CARBON decimal(1,1),
    GASES decimal(1,1),
    CONSTRAINT PK_TERMICA PRIMARY KEY (PNOMBRE),
    CONSTRAINT FK_TERMICA_PRODUCTOR FOREIGN KEY (PNOMBRE) REFERENCES PRODUCTOR (PNOMBRE)
);

create table compra
(
    PNOMBRE varchar(20),
    TNOMBRE varchar(20),
    MATRICULA varchar(8),
    SNOMBRE varchar(20),
    PAIS varchar(20),
    CANTIDAD decimal(1,2),
    CONSTRAINT PK_COMPRA PRIMARY KEY (PNOMBRE, TNOMBRE, MATRICULA, SNOMBRE, PAIS),
    CONSTRAINT FK_COMPRA_NUCLEAR FOREIGN KEY (PNOMBRE) REFERENCES NUCLEAR (PNOMBRE),
    CONSTRAINT FK_COMPRA_TRANSPORTISTA FOREIGN KEY (TNOMBRE, MATRICULA) REFERENCES TRANSPORTISTA (TNOMBRE, MATRICULA),
    CONSTRAINT FK_COMPRA_SUMINISTRADOR FOREIGN KEY (SNOMBRE, PAIS) REFERENCES SUMINISTRADOR (SNOMBRE, PAIS)
);

create table Transportista
(
    TNOMBRE varchar(20),
    MATRICULA varchar(8),
    HORASCONDUCIDAS decimal(1,1),
    CONSTRAINT PK_TRANSPORTISTA PRIMARY KEY (TNOMBRE, MATRICULA)
);

create table Suministrador
(
    SNOMBRE varchar(20),
    PAIS varchar(20),
    STOCK decimal(1,1),
    CONSTRAINT PK_SUMINISTRADOR PRIMARY KEY (SNOMBRE, PAIS)
);